# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GIN-WALLET-SERVICES]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8008


mongo:
  host: ''
  database: ''
  username: ''
  password: ''